spring.application.name=EmployeeManagement-System

spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Application logs
logging.level.in.mindcraft=INFO //it enables info level  logging for package

# Save logs into a file
logging.file.name=logs/student-management.log //saves the applicatsion logs into a log file